// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BuildPackage(arg1, arg2) {
  return window['go']['main']['App']['BuildPackage'](arg1, arg2);
}

export function InitTemplate(arg1) {
  return window['go']['main']['App']['InitTemplate'](arg1);
}

export function LoadManifest(arg1) {
  return window['go']['main']['App']['LoadManifest'](arg1);
}

export function SaveManifest(arg1, arg2) {
  return window['go']['main']['App']['SaveManifest'](arg1, arg2);
}

export function SelectDir() {
  return window['go']['main']['App']['SelectDir']();
}

export function SelectSaveFile(arg1) {
  return window['go']['main']['App']['SelectSaveFile'](arg1);
}
