// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BuildPackage(arg1:string,arg2:string):Promise<void>;

export function InitTemplate(arg1:string):Promise<void>;

export function LoadManifest(arg1:string):Promise<string>;

export function SaveManifest(arg1:string,arg2:string):Promise<void>;

export function SelectDir():Promise<string>;

export function SelectSaveFile(arg1:string):Promise<string>;
